## MAKEFILE COURSE ##

#Chapter 01: Hello World

## Basic Structure

# target:	dependencies
# [TAB]command

# DON'T FORGET TO USE TAB AFTER EACH INSTRUCTION!

# Using Make on Terminal -> A Makefile file will be searched
# 													and its instructions will be executed.

# Use @ to do silent messages

all:
	@echo "Hello World!!!!"
	echo "This instruction will appear on terminal"